### PR TITLE
Move to newer version of mithril and write code in a more component based approach

### PR DESCRIPTION
**Pull request by nordfjord**
Hi, I looked over the code, updated the whole of the application using m.component where applicable.

I mainly did this because I saw you were using **defineGetter** which has been scrapped so it might only be a while before your code would stop working.

Regards,
Einar

### CODE REVIEW

**Comment by StephanHoyer** [comment]
Thanks for your work but I don't think this makes the code better to read. The main purpose of this project is to get a first overview on how to start with mithril. As you might have seen the commits are organized to introduce mithril step-by-step.

Also there are some things that I do differently in my mithril projects:
- I don't ever use `this`. It's confusing.
- I don't use components if I don't have to. Since you can replace every view with a component later one, I don't do this in advance, since in complicates everything
- I don't want to split this I multiple files -> makes all more complicated
- I only rarely use `m.prop` or `m.withAttr` since I find it does not simplifies as much as it complicates since it's another thing you have to explain. It's not essential to understand how genius mithril is

The only thing that would be cool to have is an update of `mithril` and the `m.request` stuff.

Don't get me wrong, I appreciate your work. But this projects goal is not to write perfect mithril code but to give an easy introduction to it.

**Comment by nordfjord** [comment]
Duly noted, I had a friend over who was inquiring about mithril, found your project and decided to rewrite it with him to show him a bit about mithril. I just thought I'd share it with you in case you found any of it useful.

As for your points.

I have no quarrels about using `this`, as long as I don't need to use `Function.bind`. Furthermore I used this in some cases and defined variables in others to show that you weren't locked into a specific pattern with regards to controllers.

I tend to write components rather than view functions when it makes sense, and I thought it did in this case (not necessary but makes sense, it saved a lot of trouble with checkmarks being wrong, try opening your application, checking all todos, going to the completed view, and uncheck the first, notice how the checkmark is wrong now?) In fact for this example application I would think it necessary to explain key-ing.

On your third point I completely agree, it was a massive oversight.

with regards to m.prop and m.withAttr, I find them relatively easy to explain, as for them not being essential, I can agree with that sentiment, but they however are massively useful.

I'll close this now.

**Comment by StephanHoyer** [comment]
@nordfjord I highly appreciate your feedback. Thanks for this.

Maybe we can make a complete tutorial from this.

Or even a book about mithril. I thought doing this for quite a while. To do this together with other mithril-enthusiasts would be great.

Sounds interesting?

**Comment by nordfjord** [comment]
Absolutely, I'd love to help in any way possible.

**Pull request closed without merging**
